/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatementsRouteImport } from './routes/statements'
import { Route as SendMoneyRouteImport } from './routes/send-money'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SendMoneyIndexRouteImport } from './routes/send-money.index'
import { Route as TransactionsIdRouteImport } from './routes/transactions.$id'
import { Route as SendMoneySuccessRouteImport } from './routes/send-money.success'
import { Route as SendMoneyConfirmRouteImport } from './routes/send-money.confirm'

const StatementsRoute = StatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => rootRouteImport,
} as any)
const SendMoneyRoute = SendMoneyRouteImport.update({
  id: '/send-money',
  path: '/send-money',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SendMoneyIndexRoute = SendMoneyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SendMoneyRoute,
} as any)
const TransactionsIdRoute = TransactionsIdRouteImport.update({
  id: '/transactions/$id',
  path: '/transactions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SendMoneySuccessRoute = SendMoneySuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => SendMoneyRoute,
} as any)
const SendMoneyConfirmRoute = SendMoneyConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => SendMoneyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/send-money': typeof SendMoneyRouteWithChildren
  '/statements': typeof StatementsRoute
  '/send-money/confirm': typeof SendMoneyConfirmRoute
  '/send-money/success': typeof SendMoneySuccessRoute
  '/transactions/$id': typeof TransactionsIdRoute
  '/send-money/': typeof SendMoneyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/statements': typeof StatementsRoute
  '/send-money/confirm': typeof SendMoneyConfirmRoute
  '/send-money/success': typeof SendMoneySuccessRoute
  '/transactions/$id': typeof TransactionsIdRoute
  '/send-money': typeof SendMoneyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/send-money': typeof SendMoneyRouteWithChildren
  '/statements': typeof StatementsRoute
  '/send-money/confirm': typeof SendMoneyConfirmRoute
  '/send-money/success': typeof SendMoneySuccessRoute
  '/transactions/$id': typeof TransactionsIdRoute
  '/send-money/': typeof SendMoneyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/send-money'
    | '/statements'
    | '/send-money/confirm'
    | '/send-money/success'
    | '/transactions/$id'
    | '/send-money/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/statements'
    | '/send-money/confirm'
    | '/send-money/success'
    | '/transactions/$id'
    | '/send-money'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/send-money'
    | '/statements'
    | '/send-money/confirm'
    | '/send-money/success'
    | '/transactions/$id'
    | '/send-money/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SendMoneyRoute: typeof SendMoneyRouteWithChildren
  StatementsRoute: typeof StatementsRoute
  TransactionsIdRoute: typeof TransactionsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/statements': {
      id: '/statements'
      path: '/statements'
      fullPath: '/statements'
      preLoaderRoute: typeof StatementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-money': {
      id: '/send-money'
      path: '/send-money'
      fullPath: '/send-money'
      preLoaderRoute: typeof SendMoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-money/': {
      id: '/send-money/'
      path: '/'
      fullPath: '/send-money/'
      preLoaderRoute: typeof SendMoneyIndexRouteImport
      parentRoute: typeof SendMoneyRoute
    }
    '/transactions/$id': {
      id: '/transactions/$id'
      path: '/transactions/$id'
      fullPath: '/transactions/$id'
      preLoaderRoute: typeof TransactionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-money/success': {
      id: '/send-money/success'
      path: '/success'
      fullPath: '/send-money/success'
      preLoaderRoute: typeof SendMoneySuccessRouteImport
      parentRoute: typeof SendMoneyRoute
    }
    '/send-money/confirm': {
      id: '/send-money/confirm'
      path: '/confirm'
      fullPath: '/send-money/confirm'
      preLoaderRoute: typeof SendMoneyConfirmRouteImport
      parentRoute: typeof SendMoneyRoute
    }
  }
}

interface SendMoneyRouteChildren {
  SendMoneyConfirmRoute: typeof SendMoneyConfirmRoute
  SendMoneySuccessRoute: typeof SendMoneySuccessRoute
  SendMoneyIndexRoute: typeof SendMoneyIndexRoute
}

const SendMoneyRouteChildren: SendMoneyRouteChildren = {
  SendMoneyConfirmRoute: SendMoneyConfirmRoute,
  SendMoneySuccessRoute: SendMoneySuccessRoute,
  SendMoneyIndexRoute: SendMoneyIndexRoute,
}

const SendMoneyRouteWithChildren = SendMoneyRoute._addFileChildren(
  SendMoneyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SendMoneyRoute: SendMoneyRouteWithChildren,
  StatementsRoute: StatementsRoute,
  TransactionsIdRoute: TransactionsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
